version: "3.10"
services:
  fastline:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: fastline:v1
    environment:
      - PORT=8020
    env_file:
      - ./web/.env
    ports:
      - "8001:8020"
    